- name: openSUSE new install setup
  hosts: all
  vars:
    current_user: "{{
        lookup('env', 'USER')
        if
          ansible_host == 'localhost'
            and
          ansible_connection == 'local'
        else
          ansible_user
      }}"

  roles:

    - role: wsl
      tags:
        - wsl

    - role: package
      tags:
        - package

    - role: ping
      tags:
        - ping

    - role: zsh
      tags:
        - zsh

    - role: homebin
      tags:
        - homebin

    - role: vim
      tags:
        - vim

    # NOTE: See notes on the role task.
    - role: fstab
      tags:
        - fstab
        - never

