# tasks for zsh role

- name: System-wide Zsh setup
  become: true
  block:

    - name: Install zsh & fzf
      community.general.zypper:
        state:              present
        disable_recommends: false
        name:
          - zsh
          - fzf
          - fzf-zsh-integration

    - name: Set zsh as current user login shell
      user:
        name:  "{{ current_user }}"
        shell: /bin/zsh

    - name: Set system-wide zshrc
      copy:
        src:  zsh.zshrc.local
        dest: /etc/zsh.zshrc.local

    - name: Install govc completion
      import_tasks: govc-completion.yaml

- name: Install user's zshrc
  tags:
    - zshrc
  copy:
    src:  zshrc
    dest: ~/.zshrc

- name: Install Oh My Zsh
  import_tasks: oh-my-zsh.yaml

