# tasks for zsh role

- name: Installing zsh & fzf
  become: true
  community.general.zypper:
    state:              present
    disable_recommends: false
    name:
      - zsh
      - fzf
      - fzf-zsh-integration

- name: Setting zsh as current user login shell
  become: true
  user:
    name:  "{{ current_user }}"
    shell: /bin/zsh

- name: Setting system-wide zshrc
  become: true
  copy:
    src:  zsh.zshrc.local
    dest: /etc/zsh.zshrc.local

- name: Installing user's zshrc
  tags:
    - zshrc
  copy:
    src:  zshrc
    dest: ~/.zshrc

- name: Installing Oh My Zsh
  import_tasks: oh-my-zsh.yaml

# Doesn't work
- name: Installing govc completion
  when: false
  import_tasks: govc-completion.yaml

