# tasks for ping role

- name: Installing libcap-progs
  become: true
  community.general.zypper:
    name:               libcap-progs
    state:              present
    disable_recommends: false

- name: Checking ping capability
  changed_when: false
  shell: getcap /usr/bin/ping
  register: ping_cap

- name: Enabling ping
  become: true
  when: ping_cap.stdout == ""
  shell: setcap cap_net_raw+p /usr/bin/ping

