# tasks for ping role

- name: ping fix
  become: true
  block:

    - name: Install libcap-progs
      community.general.zypper:
        name:               libcap-progs
        state:              present
        disable_recommends: false

    - name: Check ping capability
      changed_when: false
      shell: getcap /usr/bin/ping
      register: ping_cap

    - name: Enable ping
      when: ping_cap.stdout == ""
      shell: setcap cap_net_raw+p /usr/bin/ping

