# tasks for wsl role

- name: WSL setup
  tags:
    - wsl
  become: true
  block:

    - name: Install WSL config
      import_tasks: wsl_config.yaml

    - name: Fix WSLg
      import_tasks: fix_wslg.yaml

