# tasks for wsl role

- name: 'Setting WSL config: automount'
  become: true
  community.general.ini_file:
    path:    /etc/wsl.conf
    section: automount
    option:  options
    value:   metadata,umask=022,fmask=111

- name: 'Setting WSL config: systemd'
  become: true
  tags:
    - systemd
    - never
  community.general.ini_file:
    path:    /etc/wsl.conf
    section: boot
    option:  systemd
    value:   'true'

