# tasks for homebin tasks

- name: Ensure ~/bin/ directory existence
  file:
    path:  ~/bin
    state: directory

- name: Install local scripts to ~/bin
  copy:
    src:  "{{ item }}"
    dest: ~/bin/{{ item }}
    mode: "0755"
  loop:
    - asinfo
    - ipinfo
    - wt

