# tasks for package role

- name: Packages setup
  become: true
  block:

    - name: Install general packages
      community.general.zypper:
        name:               '{{ packages.present }}'
        state:              present
        disable_recommends: false

    - name: Uninstall unneeded packages
      when: packages.absent is defined
      community.general.zypper:
        name:       '{{ packages.absent }}'
        state:      absent
        clean_deps: true

    - name: Install wslu
      tags:
        - wslu
      import_tasks: wslu.yaml

