# neowofetch tasks for package role

- name: Uninstalling neofetch
  become: true
  community.general.zypper:
    name:       neofetch
    state:      absent
    clean_deps: true

- name: Installing neowofetch
  become: true
  community.general.zypper:
    name:               neowofetch
    disable_recommends: false

