# wslu tasks for package role

- name: Check existing wslu repo file
  stat:
    path: /etc/zypp/repos.d/wslutilities-wslu-opensuse-tumbleweed.repo
  register: wslu_repo_file

- name: wslu repo
  when: not wslu_repo_file.stat.exists
  block:

    - name: Import wslu repo
      get_url:
        url:  https://copr.fedorainfracloud.org/coprs/wslutilities/wslu/repo/opensuse-tumbleweed/wslutilities-wslu-opensuse-tumbleweed.repo
        dest: /etc/zypp/repos.d/wslutilities-wslu-opensuse-tumbleweed.repo
        mode: '0644'
      register: wslu_repo

    - name: Refresh wslu repo
      when: wslu_repo.changed
      shell: >-
        zypper --non-interactive modifyrepo --enable --no-gpgcheck --refresh
        copr:copr.fedorainfracloud.org:wslutilities:wslu
        &&
        zypper --non-interactive --gpg-auto-import-keys refresh
        copr:copr.fedorainfracloud.org:wslutilities:wslu

- name: Install wslu
  community.general.zypper:
    name:               wslu
    disable_recommends: false

